### ISSUE TITLE
Question: MDSplus repository signatures

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#1040]
Dear all,

I have a question. I receive the following warning when updating MDSplus on Ubuntu 17.04. Could it be due to the fact that the OS version does not match with that of the repository?

```
$ wget http://www.mdsplus.org/dist/mdsplus.gpg.key
--2017-09-24 17:26:04--  http://www.mdsplus.org/dist/mdsplus.gpg.key
Resolving www.mdsplus.org (www.mdsplus.org)... 198.125.176.220
Connecting to www.mdsplus.org (www.mdsplus.org)|198.125.176.220|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3356 (3.3K) [text/plain]
Saving to: ‘mdsplus.gpg.key’

mdsplus.gpg.key                  100%[=======================================================>]   3.28K  --.-KB/s    in 0s      

2017-09-24 17:26:04 (23.1 MB/s) - ‘mdsplus.gpg.key’ saved [3356/3356]

$ sudo apt-key add mdsplus.gpg.key
OK
$ sudo apt-get update
Hit:1 http://it.archive.ubuntu.com/ubuntu zesty InRelease
Hit:2 http://security.ubuntu.com/ubuntu zesty-security InRelease                                                          
Hit:3 http://it.archive.ubuntu.com/ubuntu zesty-updates InRelease                                                         
Hit:4 http://it.archive.ubuntu.com/ubuntu zesty-backports InRelease                                 
Get:5 http://www.mdsplus.org/dist/Ubuntu16/repo MDSplus InRelease [3,349 B]   
Ign:5 http://www.mdsplus.org/dist/Ubuntu16/repo MDSplus InRelease
Fetched 3,349 B in 0s (7,041 B/s)
Reading package lists... Done
W: GPG error: http://www.mdsplus.org/dist/Ubuntu16/repo MDSplus InRelease: The following signatures were invalid: 15616B36D4C5040D5F57411BAD02EF6EB09CB563
W: The repository 'http://www.mdsplus.org/dist/Ubuntu16/repo MDSplus InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by AndreaRigoni** [comment]
Dear alkhwarizmi,
I just tried with the latest Ubuntu LTS version (16.4) and what happens to me is that it complains with a weak digest algorithm for the Signature:
W: http://www.mdsplus.org/dist/Ubuntu16/repo/dists/MDSplus/InRelease: Signature by key 15616B36D4C5040D5F57411BAD02EF6EB09CB563 uses weak digest algorithm (SHA1)

The problem is that the SHA-1 algorithm has been dropped in the new version
https://juliank.wordpress.com/2016/03/14/dropping-sha-1-support-in-apt/

Until the update of our signature as described here:
https://unix.stackexchange.com/questions/387053/debian-9-apt-and-gpg-error-inrelease-the-following-signatures-were-inva/387054

I would suggest you to add this line to apt/sources.list

**deb [trusted=yes] http://www.mdsplus.org/dist/Ubuntu16/repo MDSplus stable**

this will fix the issue

**Comment by tfredian** [comment]
This should now be fixed. A new stronger gpg key has been created for signing the MDSplus repositories. Users will need to install a new key for the repository on debian based platforms by doing:

```
$ wget http://www.mdsplus.org/dist/mdsplus.gpg.key
$ sudo apt-key add mdsplus.gpg.key
```
