### ISSUE TITLE
Problem with MDSplus tests --- failing tests but build completing successfully

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1111]
I don't fully understand the current testing procedures and their behavior. There are several issues that I think should be addressed with somewhat high priority:

1) Individual tests failing but build completes successfully.

 http://jenkins.mdsplus.org/job/fc25/1609/consoleFull shows:
    00:05:10.178 FAIL: segmentsUnitTest.py (and others similar failures)
    and yet:
    00:29:51.820 Finished: SUCCESS

2) Very difficult to find and understand the failures.
    Apparently the valgrind plugin and tap reports no longer work very well. Going through the artifacts for the build it is difficult to find logs or xml files that provide much information about the errors. We either need to fix this or completely disable the current testing framework and simply use the console logs for displaying the errors.

If possible it would be great if Andrea and Timo could work together on this as soon as they have some spare time to get this resolved. At this point it is difficult to know if we are getting test failures and ignoring them or the failing tests are being ignored on purpose. I think this is a serious problem that needs to be addressed.

**Comment by AndreaRigoni** [comment]
Hi Tom,
I took a look on the console you posted and it seems to me that all the FAILS are related to valgrind issues.
At a certain point you asked me to disable the failure of make process that fires valgrind tests in favor of the sanitizer because valgrind seemed very prone to fail, and it ends up in a descriptive xml recollected by jenkins plugin.

Now I see that the valgrind jenkins plugin is not working well, but the behavior of not stopping the compilation is what we expected. As far as I recall, if you like to change it it should be easy.

Andrea

**Comment by tfredian** [comment]
Hi Andrea,

Are we disabling all valgrind test failures from causing a build failure? If so, is there any point in doing valgrind tests at all? (Note: there was also a cpp test failure 00:27:06.586 FAIL: MdsTreeNodeTest
)

Do we understand the reason for the valgrind failures? Is it a problem with valgrind or is it finding real problems? Are the problems always related to particular tests and/or platforms? Do we need to provide finer test selections to disable certain types of tests (i.e. disable segmentUnitTest on fc25 during valgrind memcheck)? If we should continue with valgrind testing can we repair the valgrind plugin again so we can at least determine the reason for the failure? I couldn't seem to find the artifacts that matched the failed tests for some reason to see why it failed.

Thanks,
Tom

**Comment by AndreaRigoni** [comment]
Hi Tom, 
 Super ! I can see now at least the list of tests with errors in jenkins.

A couple of thoughts:

One problem seems to be that the source directory disappears from workspace (because it links to the git branch build I suppose) and the plugin finds any more the access to the code files to make the nice stack trace page.

A second problem is that there is any trace of whether the tests come from 32 or 64 bit directory, I think it does a copy of the xml file somewhere without the path and this is particularly bad if the test file name is repeated in multiple directories (i.e. 32 and 64 bit folders) because the last file hides the previous one with the same name. I propose, but it is clearly a temporary solution, to split the compilation of valgrind tests in multiple builds... we could select a distribution candidate for the vlgrinds tests and perform them only for that distro, splitting 32bit, 64bit, armhf .. and so on in different builds with proper name ( fc26_32, fc26_64 ). This should bring a slight speed improvement due to the added build parallelism.

A final consideration we already discussed during the meeting would be to avoid valgrind checks in python at all, that would relieve us form the usual fight with the suppressing of python itself. As Keith stated we should perform tests inside each library and not using python api to call it. I know this is due to the lack of coverage of the underlying tests I should have already done, so I blame on myself at first.


Andrea

**Comment by AndreaRigoni** [comment]
Hi Tom and Timo,
I think I just found the actual problem with the valgrind tests (my fault).

To pass from a "make tests" to a "make tests-valgrind" we must do a clean in the middle. This because if the build is done for valgrind a particular compile option is needed. This is a build script issue that should recognize it and recompile and I didn't added this option. The problem is that if we do a make clean it wipes the .log and .tap files out. We could either decide to run the valgrind tests in a separate build that will automatically solve the issue, or we could do the clean and accept that the tap output will be overridden by the valgrind one.

**Comment by zack-vii** [comment]
Hi,
I just read this issue first time today, here are few things:
* I would not deactivate the valgrind checks for python as they have proven vital to the treectx management and revealed many issues in underlying libs.
* The python suppression works fine under 64 bit. One could consider deactivating valgrind for 32 bit.
* The tests could follow the rule: if normal test fails don't start valgring tests. This way no interesting log file will be overwritten.
* (as i mentioned in the mail) if this is no problem with make tests one should compile with the valgrind settings at anytime if (valgrind is available/enabled and debug is enabled) to allow for a "make all tests tests-valgrind" without clean

**Comment by AndreaRigoni** [comment]
Side-note: The plugin was restored and now seems to work, it is waiting for the next pr but it worked for fc26 and the stack trace is visible http://jenkins.mdsplus.org/job/fc26/11/valgrindResult/pid=12319,0x0/ (at least for the cpp function). And seems that some further suppression are required.

**Comment by tfredian** [comment]
We're making quite a bit of progress. The problem reported in the exit handler of mdsip seemed to have disappeared for no apparent reason. Right now it appears that we only have one race condition left to solve and perhaps then we could perhaps enable the valgrind test failures to fail the builds. We might consider adding a build.sh option to disable valgrind from failing the build in case we need to temporarily disable valgrind failures.
