### ISSUE TITLE
mdstcl input from external files

### ISSUE THREAD

**Issue by juhi1296** [MDSplus/mdsplus#1176]
How to give external files as input to mdstcl?

**Comment by tfredian** [comment]
You can use the @ command (TCL> help @ ). If you do something like:

TCL> @/home/twf/mycmds

It will try to execute the tcl commands found in the file called /home/twf/mycmds.tcl. You can include the file type in the files specification otherwise it will use the lowercase extension based on the mdsdcl utility you are using. For example: CCL> @mycmds will look for mycomds.ccl.
