### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by juhi1296** [MDSplus/mdsplus#1188]
Hello, 
I am new to MDSplus and trying to run a java file 
![screenshot from 2018-01-01 11-43-23](https://user-images.githubusercontent.com/20973858/34465921-05072972-eee9-11e7-8a48-05a6ccaea2c6.png)

But while compiling this code, I am getting the following error
![screenshot from 2018-01-01 11-44-19](https://user-images.githubusercontent.com/20973858/34465925-210a9050-eee9-11e7-9126-4806aad14a1f.png)

Can anyone please help?
Thanks

**Comment by kgerickson** [comment]
Don't import MDSplus.*

**Comment by juhi1296** [comment]
I am still getting the same error even when I am not importing MDSplus.*

![screenshot from 2018-01-02 09-50-56](https://user-images.githubusercontent.com/20973858/34474242-775e36dc-efa2-11e7-936d-f2391fbcd1e1.png)
![screenshot from 2018-01-02 09-51-29](https://user-images.githubusercontent.com/20973858/34474250-917634b6-efa2-11e7-83ea-a3a0e8752944.png)

**Comment by GabrieleManduchi** [comment]
The problem you get with String declaration stems from the fact that there is another String class declared in the MDSplus package. Therefore you should specify explicitly java.lang.String

I recommend not to import MDSplus.* in order to avoid this.  Please be aware that in this case you must specify the package in the MDSplus class declarations. For example:

MDSplus.Tree myTree = new MDSplus.Tree(<name>, shot);

**Comment by juhi1296** [comment]
Hello, I am getting the following error :




![screenshot from 2018-01-03 10-34-02](https://user-images.githubusercontent.com/20973858/34509639-491d18e4-f072-11e7-89e0-425941ae52bf.png)

![screenshot from 2018-01-03 10-34-15](https://user-images.githubusercontent.com/20973858/34509740-6aa8fcc0-f073-11e7-8380-503a3137cfd7.png)

**Comment by GabrieleManduchi** [comment]
You must specify the package also in the exception declaration

...
}catch(MDSplus.MdsException){...

**Comment by juhi1296** [comment]
Yes Done.
Thank You!
