### ISSUE TITLE
[Feature request] Support for named dimensions

### ISSUE THREAD

**Issue by lamorton** [MDSplus/mdsplus#1214]
It would be helpful to have a way to provide and retrieve dimension names for arrays that have dimensions. In some cases, if the dimension is stored as a reference to another node, it is possible to extract the name of the dimension that way.  However, for most compound signals, it looks like the dimensions are anonymous.  It's often possible for a user to infer the name of the dimension by looking at the units and values and shapes, but sometimes it is ambiguous (take for instance the EFIT 65x65 array - the array shape isn't helpful because R,Z arrays are both 65 long), and units are not always available.

**Comment by zack-vii** [comment]
hm, it is possible to add a help tag to any data. which possibly could be used to add information about dimensions as well. Its debatable if one would want to use this for segmented nodes because one would have to store it for each segment. another way would be to add subnodes nodes to the signal containing the definition of the dimensions. since the optimal way of solving this problem is very much depending on the way the data is stored it is unlikely we would pin one down. We would rather implement a new option to add meta-information to nodes that would be accessible with the getHelp (#829) which one could exploit for this.
