### ISSUE TITLE
userdefined source dir is reflected in gdb hooks

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1246]
If you gdb an MDSplus application of the current build the source files are expected to be localized in
/mdsplus-j2/jenkins/1-pull-request-test

Since we can control the mapping or the source directory within the docker image we should try to match the paths with a more meaningful location.

Is there a package you can get via dfn/apt.. that installs the source into a system folder.

**Comment by tfredian** [comment]
Well there are two easy solutions to this issue. In gdb you can use the "directory" command to modify the search path for finding the sources. You could also run gdb inside a docker and mount your local source directory on /mdsplus-j2/jenkins/1-alpha-release with the -v option.

docker run -ti -v /usr/local/mdsplus:/usr/local/mdsplus -v /home/user/mdsplus:/mdsplus-j2/jenkins/1-alpha-release mdsplus/docker:fc25 /bin/bash

I assumed you meant a release build instead of pull request since you probably want to debug programs installed on your system that were built by jenkins.

**Comment by zack-vii** [comment]
yes i meant the release builds. installed on a user machine without docker
