### ISSUE TITLE
Problem in jScope retrieving DTYPE_F data using the MdsDataProvider class

### ISSUE THREAD

**Issue by merlea** [MDSplus/mdsplus#1297]
For TCV data, we store some of our references as VMS floats (DTYPE_F). When read in jScope the data is not displayed correctly. We use the MdsDataProvider class.

If we modify the expression and cast the data to float, the data is displayed correctly, e.g.
\PCS::DRAW_FEEDFOR_GAS:ALIM_001 fails while
float(\PCS::DRAW_FEEDFOR_GAS:ALIM_001) succeeds

I imagine the problem is in the DataProvider layer as specifying a simple signal as BUILD_SIGNAL([0F0,1F0,0F0],*,BUILD_DIM(*,[0,1,2])) shows no problem when displaying the data.

This happens for both alpha and stable versions.

Let me know if you need more details,
Antoine.

**Comment by GabrieleManduchi** [comment]
Dear Antoine,
    in order to track the issue I would need a pulse file containing the 
data. Is it possible to make a copy of  it in some way?

                                         Gabriele

-- 
Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by merlea** [comment]
Dear Gabriele,
Is it enough if we provide you access to the TCV server (it seems like you already have an account here).
Otherwise yes we can certainly get a copy.
Antoine.

**Comment by merlea** [comment]
Here is a copy of one shot file that contains the trace
\PCS::DRAW_FEEDFOR_GAS:ALIM_001

[pcs_55555.tar.gz](https://github.com/MDSplus/mdsplus/files/1967486/pcs_55555.tar.gz)

Maybe of notable importance is the fact that we have an older version of jScope (circa April 2015, stable_release-6-1-83 appears as one of the latest item in the Changelog) that does display correctly the traces. So the bug must come from some change since then ...

Antoine.

**Comment by GabrieleManduchi** [comment]
I have issued a pull request that fixes the issue. The server side code activated by jScope now checks for DTYPE_F data and converts it in case

**Comment by merlea** [comment]
Thanks Gabriele.

I am not sure I understand what you mean by server-side in the case of
jScope. Does this mean that we'll have to update the software on our MDS+
server or only locally where we have jScope installed?
For me only the second option would make sense as previous versions of
jScope handled this properly.

Antoine.


Le mer. 2 mai 2018 à 18:44, GabrieleManduchi <notifications@github.com> a
écrit :

**Comment by GabrieleManduchi** [comment]
The fix is in server side code (ScopeUtilities.c in MdsMish library)that is invoked via mdsip by jScope MdsDataProvider. This component provides on the fly resampling to reduce the amount of data handled by jScope JVM and to reduce network traffic. It was not present in previous jScope versions. 
Therefore you need to upgrade MDSplus at the server side to make the fix effective.

**Comment by merlea** [comment]
OK. Thanks.
We will try when the pull request has been approved and let you know.

**Comment by merlea** [comment]
Hi again,

This issue is fixed with the latest alpha.

Thank you,
Antoine.
