### ISSUE TITLE
minor bug when dispatch/build is not called again after opening another shot

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1302]
mdsdcl hangs possibly due to conditional actions (WHEN is required ACTION node):
e.g.:
```tcl
set tree main
create pulse 1
set tree main/shot=1
dispatch/build
dispatch/phase INIT
...
set tree main
create pulse 1
set tree main/shot=1
dispatch/phase INIT
```
If the init phase contains conditional actions, the dispatch blocks after the first Action in the dependency list.

minor bug as it only happens during manual testing.

**Comment by tfredian** [comment]
Is this due to not doing a dispatch/build to reset the dispatch table after doing the set tree of the new pulse? If so, should we keep timestamp when a tree is opened and record that time in the dispatch table and then verify in dispatch/phase that the timestamps match? Is it worth the effort since, as you said, during normal operation the dispatching is done using a script which would not make this error.

**Comment by zack-vii** [comment]
if at all we are planning to fix this, i think easiest would be to check and clear the table on any change of the context, i.e. opening a tree or closing one,
