### ISSUE TITLE
GETNCI shows errors and segfaults in alpha

### ISSUE THREAD

**Issue by merlea** [MDSplus/mdsplus#1315]
This is the behavior I am getting at the moment (using the latest alpha):
```
$ tdic
TDI> TreeOpen("tcv_shot",55555)
265388041
TDI> getnci("\\base::pd:pd_001","path")
%TDI Error in GETNCI("\\base::pd:pd_001", "path")
%TDI Error in EVALUATE(GETNCI("\\base::pd:pd_001", "path"))
%TDI Error in EXECUTE('getnci("\\\\base::pd:pd_001","path")')

TDI> getnci("\\base::pd_ha_vertical","path")
%TDI Error in GETNCI("\\base::pd_ha_vertical", "path")
%TDI Error in EVALUATE(GETNCI("\\base::pd_ha_vertical", "path"))
%TDI Error in EXECUTE('getnci("\\\\base::pd_ha_vertical","path")')

TDI> getnci(\base::pd_ha_vertical,"path")
"\\BASE::PD_HA_VERTICAL"
TDI> getnci(getnci(\base::pd_ha_vertical,"path"),"path")
%TDI Error in GETNCI(GETNCI(\BASE::PD_HA_VERTICAL, "path"), "path")
%TDI Error in EVALUATE(GETNCI(GETNCI(\BASE::PD_HA_VERTICAL, "path"), "path"))
%TDI Error in EXECUTE('getnci(getnci(\\base::pd_ha_vertical,"path"),"path")')

TDI> getnci("\\base::pd:pd_001","fullpath")
%TDI Error in GETNCI("\\base::pd:pd_001", "fullpath")
%TDI Error in EVALUATE(GETNCI("\\base::pd:pd_001", "fullpath"))
%TDI Error in EXECUTE('getnci("\\\\base::pd:pd_001","fullpath")')

TDI> getnci("\\TCV_SHOT::TOP.BASE.MEASUREMENTS.PD:PD_001","path")
Erreur de segmentation (core dumped)
```
So specifying a node reference in getnci works, specifying a node specification yields errors and/or segfaults.

With the stable branch, everything works flawlessly
```
TDI> TreeOpen("tcv_shot",55555)
265388041
TDI> getnci("\\base::pd:pd_001","path")
"\\BASE::PD_HA_VERTICAL"
TDI> getnci("\\base::pd_ha_vertical","path")
"\\BASE::PD_HA_VERTICAL"
TDI> getnci(\base::pd_ha_vertical,"path")
"\\BASE::PD_HA_VERTICAL"
TDI> getnci(getnci(\base::pd_ha_vertical,"path"),"path")
"\\BASE::PD_HA_VERTICAL"
TDI> getnci("\\base::pd:pd_001","fullpath")
"\\TCV_SHOT::TOP.BASE.MEASUREMENTS.PD:PD_001"
TDI> getnci("\\TCV_SHOT::TOP.BASE.MEASUREMENTS.PD:PD_001","path")
"\\BASE::PD_HA_VERTICAL"
```

Could you look into it?
Thanks,
Antoine.

**Comment by tfredian** [comment]
Hi Antoine,

I was unable to reproduce this problem here running the latest alpha installation. I created a tree structure similar to the nodes referenced above and it seemed to work just fine:

[twf@cmodws106 ~]$ tdic
TDI> treeopen('tcv_shot',55555)
265388041
TDI> getnci("\\base::pd:pd_001","path")
"\\BASE::PD_HA_VERTICAL"
TDI> getnci("\\base::pd_ha_vertical","path")
"\\BASE::PD_HA_VERTICAL"
TDI> getnci(\base::pd_ha_vertical,"path")
"\\BASE::PD_HA_VERTICAL"
TDI> getnci(getnci(\base::pd_ha_vertical,"path"),"path")
"\\BASE::PD_HA_VERTICAL"
TDI> getnci("\\base::pd:pd_001","fullpath")
"\\TCV_SHOT::TOP.BASE.MEASUREMENTS.PD.PD_001"
TDI> getnci("\\TCV_SHOT::TOP.BASE.MEASUREMENTS.PD:PD_001","path")
"\\BASE::PD_HA_VERTICAL"
TDI> exit
[twf@cmodws106 ~]$ mdstcl
TCL> show version


MDSplus version: 7.42.1
Git branch: alpha
  Git tag: alpha_release-7-42-1
  View:
    https://github.com/MDSplus/mdsplus/tree/alpha_release-7-42-1
  Download:
    https://github.com/MDSplus/mdsplus/archive/alpha_release-7-42-1.tar.gz
  Git commit: 8b9a612fe7a96bf5ffd630a01de2c2d3c408f035
  Build date: Tue May 15 02:10:32 UTC 2018

So I'm not sure what is causing this on your system. Do you get similar problems if you test this using the test trees in MDSplus (main_path=mdsplus/trees and subtree_path=mdsplus/trees/subtree)? I don't know if there is something peculiar in your trees which is uncovering some MDSplus bug. If it works ok on the main/subtree trees we could try to reproduce the problem with your trees if you send me a tar file with the tsv_shot and base trees. (mailto: twf@psfc.mit.edu)

-tom

**Comment by merlea** [comment]
Hi Tom,

I did the tests you suggested and indeed I do not get any error using the test trees locally.
Now if I try to access them through MDSip, then this is where the problems start appearing (for my original report tcv_shot_path and base_path both were "tcvdata::".

Here is an example where I still get errors using the test trees on a "separate" machine using mdsip:
```
$ main_path=spcpc371:8001:: subtree_path=spcpc371:8001:: tdic
TDI> TreeOpen("main",-1)
265388041
TDI> getnci("\SUBTREE::TOP:HV1443","path")
%TDI Error in GETNCI("SUBTREE::TOP:HV1443", "path")
%TDI Error in EVALUATE(GETNCI("SUBTREE::TOP:HV1443", "path"))
%TDI Error in EXECUTE('getnci("\\SUBTREE::TOP:HV1443","path")')
```

Thanks for your help,
Antoine.

**Comment by tfredian** [comment]
Hi Antoine,

Thanks for the info. I was able to reproduce this problem here using the "thick client" mdsip tree path definitions. There definitely seems to be a bug in this tree access mode and we'll attempt to track down the problem.  As a temporary workaround you might try "distributed access" mode by defining your tree paths using:

tcv_shot_path=host[:port]::/dirspec[;host:port::/dirspect2;....]
base_path=host[:port]::/dirspect.....

I think this is how most sites define there tree paths which also allows the trees and subtrees to be located on multiple servers.

-tom
