### ISSUE TITLE
Follow-up on issue #1316 in stable

### ISSUE THREAD

**Issue by merlea** [MDSplus/mdsplus#1324]
Hi,

Thanks for looking into issue   #1316.
Unfortunately I think it is not completely fixed.
The case I provided now works but I still get an error if I provide a single string (not a string array with one element.

Here is how to reproduce it:
```
TDI> _a = MAKE_SIGNAL([0,1,2],*,MAKE_DIM(*,["A","B","C"]))
Build_Signal([0,1,2], *, Build_Dim(*, ["A","B","C"]))
TDI> _d = dim_of(_a)
Build_Dim(*, ["A","B","C"])
TDI> _a[_d]
Build_Signal([0,1,2], *, ["A","B","C"])
TDI> _a[[_d[0]]]
Build_Signal([0], *, ["A"])
TDI> _a[_d[0]]
Build_Signal([], *, [])
TDI> _a[_d[1]]
Build_Signal([], *, [])
TDI> _a[_d[2]]
Build_Signal([], *, [])
```
The error is that it returns a signal with empty data and dimension, when they should be scalars.

Here is the expected/previous behavior:
```
TDI> _a = MAKE_SIGNAL([0,1,2],*,MAKE_DIM(*,["A","B","C"]))
Build_Signal([0,1,2], *, Build_Dim(*, ["A","B","C"]))
TDI> _d = dim_of(_a)
Build_Dim(*, ["A","B","C"])
TDI> _a[_d]
Build_Signal([0,1,2], *, ["A","B","C"])
TDI> _a[[_d[0]]]
Build_Signal([0], *, ["A"])
TDI> _a[_d[0]]
Build_Signal(0, *, "A")
TDI> _a[_d[1]]
Build_Signal(1, *, "B")
TDI> _a[_d[2]]
Build_Signal(2, *, "C")
```

Best,
Antoine.

**Comment by tfredian** [comment]
Hopefully this should be fixed by the next stable release which should be available tomorrow. Once you get a chance to test this and if it works you can close this issue. I decided to just replace TdiCull.c with the current version in the alpha branch since that seems to work. I did some local testing here and building a stable version with the update TdiCull.c appear to work for me.

**Comment by merlea** [comment]
Seems to work for me too.

Thanks,
Antoine.
