### ISSUE TITLE
[Matlab] Error loading library javamds: java.lang.UnsatisfiedLinkError: no JavaMds in java.library.path

### ISSUE THREAD

**Issue by ghost** [MDSplus/mdsplus#1330]
Dear all,
I recently tried to build a MDSplus server and link the database with multiple means. I have tried Pyhton, LabView and Java on Windows, they all work perfectly. But when it comes to Matlab, no matter which edition of MDSplus I used it always comes with the same error:

```
Error loading library javamds: java.lang.UnsatisfiedLinkError: no JavaMds in java.library.path
java.lang.UnsatisfiedLinkError: no JavaMds in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at MDSplus.Data.<clinit>(Data.java:112)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.mathworks.jmi.OpaqueJavaInterface.findClass(OpaqueJavaInterface.java:181)
Error using mdsvalue (line 22)
Java exception occurred:
java.lang.UnsatisfiedLinkError: MDSplus.Data.execute(Ljava/lang/String;[LMDSplus/Data;)LMDSplus/Data;

	at MDSplus.Data.execute(Native Method)


Error in mdsopen (line 22)
       status = mdsvalue('TreeOpen($,$)', ltree, shot);
```

The javacalsspath and environment variables are set. Please help.

**Comment by tfredian** [comment]
You might take a look at: http://www.mdsplus.org/index.php/Documentation:Tutorial:MdsObjects#MATLAB_Specific_Issues

If you have already tried following those instructions you might try changing the librarypath.txt file to reference C:\Windows\SysWOW64 instead of C:\Windows\System32 if your installed Matlab is a 32-bit application. The two directories are confusing in Windows as the System32 directory contains 64-bit DLL's while the SysWOW64 directory contains 32-bit DLL's. I modified the page referenced above to include the SysWOW64 directory for 32-bit Matlab. Hope this helps.

**Comment by ghost** [comment]
Thank you very much for your reply and help.
It works. Excuse me for this kind of low level question......
Thank you again.
