### ISSUE TITLE
Matlab r2018a: Error loading library javamds: java.lang.UnsatisfiedLinkError: /usr/local/mdsplus/lib/libJavaMds.so: libMdsShr.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Leny-plasma** [MDSplus/mdsplus#1333]
Hi,

It might be a trivial issue but I cannot get MDSplus to work on Ubuntu 18.04 with Matlab R2018a. 
I followed the instruction given here:

http://www.mdsplus.org/index.php/Documentation:Tutorial:MdsObjects#MATLAB_Specific_Issues

I always get the following error:

Error loading library javamds: java.lang.UnsatisfiedLinkError: /usr/local/mdsplus/lib/libJavaMds.so: libMdsShr.so: cannot open shared object file: No such file or directory

My paths seem ok:
java.lang.System.getProperty('java.library.path')

ans =

/usr/local/MATLAB/R2018a/bin/glnxa64:/usr/local/MATLAB/R2018a/sys/jxbrowser/glnxa64/lib:/usr/local/mdsplus/lib

path

		MATLABPATH

	/usr/local/mdsplus/matlab
        ...
Any ideas?

**Comment by gronchi** [comment]
Please, check if the package mdsplus-matlab and mdsplus-java-bin had been installed: 
`sudo apt-get install mdsplus-matlab mdsplus-java-bin
`
(the mdsplus-java-bin contains the libJavaMds.so missing from you log)

**Comment by tfredian** [comment]
Actually I think it is complaining about libMdsShr.so. I suspect java.library.path is only used for finding the libraries referenced by java. The loader is not finding libMdsShr.so perhaps because LD_LIBRARY_PATH or ldconfig was not invoked during the install. If MDSplus was just recently installed then I would suggest logging out and logging back in to ensure the environment variables are set correctly when MATLAB is started.

**Comment by Leny-plasma** [comment]
Both package are installed. Login out/back didn't work. I will try to rebuild ldconfig cache

**Comment by Leny-plasma** [comment]
my ldconfig cache seems ok:
>cat /etc/ld.so.conf.d/*

/usr/lib/x86_64-linux-gnu/libfakeroot
# Multiarch support
/usr/local/lib/i386-linux-gnu
/lib/i386-linux-gnu
/usr/lib/i386-linux-gnu
/usr/local/lib/i686-linux-gnu
/lib/i686-linux-gnu
/usr/lib/i686-linux-gnu
# libc default configuration
/usr/local/lib
/usr/local/mdsplus/lib
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu

**Comment by tfredian** [comment]
I'm not entirely sure what is causing this trouble. In trying to test this on a Ubuntu18.04 system I managed to get matlab R2018a to work with MDSplus by installing mdsplus-alpha instead of the stable (did not try stable as alpha was already installed). I ran into trouble at first because there seems to be a problem with the python bridge in matlab on 18.04. The MDSplus matlab interface tries to use the java bridge and if that fails it will use the python bridge. The MDSplus matlab modules have quite a few lines of code that contain py.<python-module>.<object|function>.... and even though the java bridge was working and these python bridge statements were not being executed just having them there caused the things to break. Simply replacing py. with px. in the modules fixed the problem and I am able to open trees and read data.

```
>> mdsopen('cmod',1090909009')

ans =

  int32

   1090909009

>> x=mdsvalue('\ip');
>> size(x)  

ans =

       13312           1
```

The alpha matlab interface does a lot of the configuration for you automatically. You should only need /usr/local/mdsplus/lib in your LD_LIBRARY_PATH environment variable and the /usr/local/mdsplus/matlab directory in Matlab path. It is not clear yet why having those py lines in the code is causing problems. The MDSplus python module used on Ubuntu18.04 seems to work just fine and as I said changing the py. to px. fixes the problem but if any of those lines got executed it should have caused an error. This obviously is not a great solution but might get yours working until we attempt to add official support for Ubuntu 18.

**Comment by tfredian** [comment]
I was able to demonstrate a problem with accessing the python numpy package in matlab on u18. Accessing other modules seems to work. The MDSplus modules pull in the numpy package so perhaps the numpy package has some conflicting library dependencies with matlab. Trying just py.numpy.array() after invoking matlab generates a memory error and hangs the process:

```
>> py.numpy.array([1,2])
malloc(): memory corruption
```

**Comment by tfredian** [comment]
This should be fixed by: https://github.com/MDSplus/mdsplus/pull/1353
which is now in both alpha and stable releases.
