### ISSUE TITLE
Python tree.dir()  does not take into account tree.setDefault(node)

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1338]
after creating a tree object   
```
t.dir()
HARDWARE        STRUCTURE
SIGNALS         STRUCTURE
COMMENT         TEXT
```
shows the members and children of \TOP
after setting default to annother node it still outputs the same.
```
t.setDefault(t.SIGNALS)
t.dir()
HARDWARE        STRUCTURE
SIGNALS         STRUCTURE
COMMENT         TEXT
```

**Comment by tfredian** [comment]
According to the help string for the Tree.dir() method, this was the intended behavior. I'm not suggesting that doing the equivalent of t.getDefault.dir() would have been a better implementation but since it was introduced as behaving as t.top.dir() we need to retain this behavior so as to not break any existing applications.
