### ISSUE TITLE
remote objects on windows need scp

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1340]
To get the mdsConnection object to work on windows you not only need to have defined
ssh.bat to point to a script that runs putty's ssh with your key, but you also need to create scp.bat to invoke pscp from putty. Doing this in the obvious way did not work.

We need to figure out what should be in the scp.bat script and document it.

**Comment by joshStillerman** [comment]
I found this:
https://www.bleepingcomputer.com/news/microsoft/heres-how-to-enable-the-built-in-windows-10-openssh-client/
but have not tried it out.

There is also ssh and scp as part of  cygwin

**Comment by tfredian** [comment]
Windows 10 now provides OpenSSH versions of ssh and scp in the latest releases. The plumbum python module used by the mdsConnector does not work with this though because if detects Windows and then mangles the directory spec of things it tries to scp to the server converting C:\directory to /C/diretory,,,

It also uses the tempfile module to write a script to a temporary file and scp the file to the server but tempfiles opened on windows cannot be accessed by other processes until they are closed. I managed to get this all to work by hacking on a couple files in the plumbum module. I am thinking of adding an issue or pull request to the plumbum github project for this but have not done so yet.

**Comment by tfredian** [comment]
I submitted an issue for the plumbum python module:
https://github.com/tomerfiliba/plumbum/issues/394

**Comment by tfredian** [comment]
This is now fixed.
