### ISSUE TITLE
TreeshrHooks in python

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1349]
It may be useful to allow users to create Treeshr Hooks in python.

**Comment by joshStillerman** [comment]
We will provide hooks for all segment operations. For this can be used to prototype things that we then want to move into statically defined extra operations.  

Hooks could be stacked then we could leave them as hooks.

**Comment by tfredian** [comment]
Look into adding a useHooks flag in nci. If not set node related hooks will not be called.

**Comment by tfredian** [comment]
TDI base TreeShr hooks were added by: https://github.com/MDSplus/mdsplus/pull/1467
See that pull request for more details on the new feature.

It is not yet clear how much these hooks will be used by user sites. There are use case issues with such hooks since they will be invoked on the system where running applications call the corresponding TreeShr routines. If the functions performed by these hooks need to communicate with applications running on other systems the site will have to implement a framework used by the hook. The addition of nci flags to control which nodes invoke node specific operation hooks is a fairly large project as it will require changes to a lot of code to manipulate the flags in applications such as TCL, Traverser as well as all the object oriented api's. For this reason the addition of these nci flags will be postponed until it is clear that they would be useful. The current implementation allows users to control which hook types are invoked simply by defining an environment variable, TreeHooks.
