### ISSUE TITLE
Previous debian releases not availble

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1493]
When a new debian release is created previous releases are not available on our server. 

This means that when there is a problem with a new release you can not do:

apt-get install mdsplus-alpha-xxx=x.y.zz  

to revert to previous build.

**Comment by tfredian** [comment]
I had assumed this was possible because all of the older releases are indeed in the debian repositories and was accomplished by using the --keepunreferencedfiles option of reprepro:

       --keepunreferencedfiles
              Do  not  delete files that are no longer used because the package they are
              from is deleted/replaced with a newer version from the  last  distribution
              it was in.

The only way to retain older versions, as far as I can find, is to put each older version in another "distribution" by adding new distributions to the conf/distributions file in the repo such as MDSplus-7.60.2 thus appending to this config file for every new release of alpha and stable. It boggles the mind to try to understand the reasoning behind this choice of design for a repository! Unless someone has other ideas for adding this capability our debian based repositories will only provide the latest release. In theory users could downgrade a release manually by downloading the debian files from the repository, remove the latest version and install the debian files manually. The debian files are in a DEBS subdirectories such as: http://mdsplus.org/dist/Ubuntu16/alpha/DEBS/ and are in the as well as in the repo directory tree such as: http://www.mdsplus.org/dist/Ubuntu16/repo/pool/alpha/m/mdsplus-alpha-kernel-bin/

The fact that having the debian files in the repo does not make them available to install directly from the repo probably suggests that the --keepunreferencedfiles option is not useful and just wastes disk space.

I am adding the noremind label to this issue to disable getting issue reminders for this one.

**Comment by tfredian** [comment]
This was somewhat "fixed" by adding an MDSplus-previous component to the MDSplus repositories which contains the previous release of MDSplus. See: http://www.mdsplus.org/index.php/Latest_Ubuntu/Debian/RaspberryPi_Packages#Enabling_MDSplus_Debian_Repository_to_support_downgrading_to_the_previous_release
