### ISSUE TITLE
Handling of lists in Python MDSplus adding extra element

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1679]
Converting a python list into an MDSplus List is adding a extra element to the beginning of the List.

```
>>> from MDSplus import makeData
>>> x=makeData(['this','is','a','test'])
>>> print(x)
List(,"this","is","a","test")
```

**Comment by tfredian** [comment]
This actually seems to represent a strange behavior with List's. Continuing with the above example indicates that while the decompile of a List instance shows a leading comma the contents of the List is actually the expected 4 element list. Similarly the List creator function in tdi requires the leading comma. It seems confusing to require this leading comma and displaying the leading comma in decompile. Intuitively one would expect the constructor would be List(a,b,c,d) and the decompile would be List(a,b,c,d). Perhaps I'm missing some justification for the current behavior. It is unclear how widely List() tdi function is being used and whether changing the behavior is a good idea at this point.
```
>>> x
['this', 'is', 'a', 'test']
>>> x[0]
'this'
>>> Data.compile('List(1,2,3,4)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/MDSplus/mdsdata.py", line 469, in compile
    return TdiCompile(*args,**kwargs)
  File "/usr/lib/python2.7/site-packages/MDSplus/mdsdata.py", line 62, in TdiCompile
    return _cmp.COMPILE(expression,*_unwrap(args))._setTree(**kwargs).evaluate()
  File "/usr/lib/python2.7/site-packages/MDSplus/compound.py", line 348, in evaluate
    _exc.checkStatus(_TdiShr. TdiIntrinsic(               self.opcode,nargs,argslist,xd.ref))
  File "/usr/lib/python2.7/site-packages/MDSplus/mdsExceptions.py", line 95, in checkStatus
    raise exception
MDSplus.mdsExceptions.ApdAPD_APPEND: %APD-E-APD_APPEND, First argument must be APD or *
>>> Data.compile('List(,1,2,3,4)')
[1, 2, 3, 4]

```

**Comment by zack-vii** [comment]
he comma is required to be able to use the implementation of vector and it allows to add elements to the apd

it is used

_l=List(*,1,2,3)  -> creates a new list
_l = List(_l,4,5,6) -> appends to the list -> List(,1,2,3,4,5,6)
this is because for vector [[1,2,3],4,5,6]  results in [1,2,3,4,5,6]
In contrast to vectors, APDs may hold other APDs as argument.
Treating the first arg always as element would break the support more more than 255 elements;
Treating treating the first argument based on if class would introduce an unexpected special treatment for APT elements as fisrt element of the list.
Ergo I treat it as APD to append to and require an empty arg if I create a new list.

We should fix [,1,2,3] though as this seems to crash due to an extra free

hm might be due to the way we entangled APd.Lists with python lists but the proper decompile of a Apd.List should show the full expression now (alpha), e.g. "List(,1,2,3)"

**Comment by tfredian** [comment]
If that is the reason then I suggest we create a build_list() function that behaves as one would expect and change decompile(List) to produce BUILD_LIST(args). Users are familiar with the build_xyz() functions to build complex data types (i.e. build_signal, build_with_units) and not advertise the List() function. Don't know if the same is required for Dictionary. If it is then I would suggest doing the same, BUILD_DICTIONARY() and decompile to a BUILD_DICTIONARY().

**Comment by zack-vii** [comment]
however Build_xyz methods have two things in common.
1. the generate CLASS-R objects
2. the come together with MAKE_xyz.

Whats so problematic with List(,1,2,3) its heavily used by may apps now and common among all APD offsprings TUPLE DICTIONARY and LIST. Also its around for years by now and no one complaint so far. If anyone else uses it we would break their code too.

PS: its also documented in the wiki
http://www.mdsplus.org/index.php/Documentation:Reference:TDI_JKL#list

**Comment by tfredian** [comment]
We would not break any code if we just add a build_list fun which would have a sensible calling format.
⁣Sent from BlueMail ​

**Comment by zack-vii** [comment]
So you what to introduce aliases. but we still should not change the decompile string as execute(decompile()) would break through mdsip across versions.
I still dont see why we would need to follow with a make_ build_ notation which is used for CLASS-R descriptors.
using make_ and build_ would suggest LISTs and DICTIONARYs to be CLASS-R like descriptors when they are actually following CLASS-A structure. (the array like strructure intuitively allows you to use List(,_a,_b,_c) to pass struct descriptor** to a c function from tdi.)

If you assume the familiarity of the user with make_ and build_ functions they should fit in that line in all aspects. I just learned today in a summary meeting about a software development conference, that many organizations regret their decisions to treat different things by the same superclass just to avoid duplicate code. Since later improvements have to use complicated structure to disentangle the different subclasses.

What we should do instead is, we should make vector(,1,2,3) to work as [1,2,3]. This will allow users of the future to use all class-a like constructors the same way. currently it crashes and needs to be fixed anyway.

**Comment by tfredian** [comment]
Either I wasn't aware or (more likely) completely forgot the purpose of the leading comma in the List() "constructor". I understand now that you can append to a List and Dict or convert a Dict into a List by passing the object as the first argument. This is definitely a useful feature. I took a quick look at http://www.mdsplus.org/index.php/Documentation:Reference:TDI_JKL#list and it might be useful to add another example passing a list as the first argument. Perhaps adding some mention of the List and Dict functions to the tutorial section as well.
