### ISSUE TITLE
mdstcl 'show server' fails when server restarts

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1739]
```
TCL> sho server sparc-daq1:8123
Checking server: sparc-daq1:8123
Thu Jul 11 16:43:19 2019, sparc-daq1:mdsip_test, logging enabled, Inactive
TCL> sho server sparc-daq1:8123
Checking server: sparc-daq1:8123
Error sending data to remote server: Broken pipe
```
in between these commands I restarted the mdsip server on that port

**Comment by joshStillerman** [comment]
if on the otherhand your mdstcl tells it to stop, the behavior is better:
```
TCL> sho server sparc-daq1:8123
Checking server: sparc-daq1:8123
Thu Jul 11 16:47:01 2019, sparc-daq1:mdsip_test, logging enabled, Inactive
TCL> stop server sparc-daq1:8123
TCL> sho server sparc-daq1:8123
Checking server: sparc-daq1:8123
Error in connect to service: Transport endpoint is not connected
Error connecting to server
TCL> sho server sparc-daq1:8123
Checking server: sparc-daq1:8123
Thu Jul 11 16:47:15 2019, sparc-daq1:mdsip_test, logging enabled, Inactive
TCL> 

```

**Comment by zack-vii** [comment]
Well the reason for this is the client uses the host:port combination as identifier to reuse a formerly established connection from a list. However due to the restart of the server the other end of the socked has been closed. and the connection attempt fails, hence the error message. If you do "stop server" the client knows that this will close the connection and remove the connection from from the list right after sending the stop_server command. A consecutive call of "show server" will find no open connection to server:host and open an new connection with a fresh port. 

Solution could be to implement a retry once either in io_send or one of the higher level methods. Possibly you would want to know if the server restarted during a request so you wont sendArgs to a server that did not get the expression. Or you might have been interested in a tdi context that now has been wiped. One could also let it slide and just warn the user if the connection had to be renewed via a new status. The server would either fail, e.g. because the tdi context does not hold the var requested or reject the args if it missed the expression.

**Comment by zack-vii** [comment]
@joshStillerman : seems to work now. does it work for you too
