### ISSUE TITLE
Python MDSplus.Event - messagenot sent on one of connected networks

### ISSUE THREAD

**Issue by VadimNV** [MDSplus/mdsplus#1746]
Dear MDSplus developers team,

  I have several network cards on my (CentOS) Linux machine and two (ethernet) network interfaces set up. They are configured to two different IP/Port addresses (e.g. typing “ip a” shows the relevant info):
eno1: IP-1/PORT-1
eno2: IP-2/PORT-2

  where eno1 and eno2 are the names of my ethernet networks. When I use Python or Matlab interface to MDSplus and send a UDP message, e.g.
…
from MDSplus import Event
from numpy import *
Event.seteventRaw("test message",fromstring("OA: Test Events from Python;",uint8))
…
  the message gets sent on whichever network appears to be “first” in the list, in my case eno1. 
  Consequently, computers connected to eno1 network can receive these messages and computers on the eno2 network cannot. 

  Ideally, I would like to broadcast UDP messages on both networks. 
  At the very least, I’d like to be able to choose which network to use for broadcasting, e.g. eno2. 
  How can I do this?

  Thanks in advance.
 Vadim

**Comment by tfredian** [comment]
Hi Vadim,

Sorry for taking so long to reply to this issue!! We had added some enhancements to the events to enable users to change some of the settings for the event broadcasting but that feature was never documented on the mdsplus web site.

There should be a file called /usr/local/mdsplus/xml/eventsConfig.xml in your MDSplus installation which documents the available settings.  If you copy that file to either a directory called ~/.mdsplus/ or /usr/local/mdsplus/local/ and specify the interface (i.e. "en02") for the IP_MULTICAST_IF option this should let you send the multicast to a different interface. You can optionally just specify the interface by creating an environment variable called mdsevent_interface. Unfortunately these settings are only loaded once when your process is run so you won't be able to switch between interfaces in a single process by changing the environment variable.

Again, sorry for not responding sooner. Let me know if this solves you problem. Since this feature was not widely advertised it undoubtedly has not been thoroughly tested in the community. If it works for you I'll add some documentation for it to the www.mdsplus.org wiki.

-tom

**Comment by VadimNV** [comment]
Dear Tom,

  Thanks a lot for your clear solution walk-through. It works as expected.

Regards,
Vadim
