### ISSUE TITLE
Some dispatched action replies are not getting sent   / recieved

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1760]
A user reported that his dispatched actions were hanging about 50% of the time.
I verified that it is exactly 50% of the time (every other)

If you run a program that dispatches an action and exits
and then you run that program again it hangs.

This is because the socket management code in `SendReply` in `servershr\ServerQAction.c` is not working.

Given a script:
```
$ cat t.tcl
set tree lh
create pulse 'P1'
set tree lh /shot = 'P1'
dispatch .HARDWARE.SEND_INIT
$ 
```
and an action:
```
TCL> deco .hardware.send_init
Build_Action(Build_Dispatch(2, "SUBMIT_SERVER", "INIT", 1, ""), LHInitialize($SHOT), "")
TCL>
```
This HANGS
```
[jas@cmodws107 ~]$ mdstcl
TCL> @t.tcl 33
TCL> exit
[jas@cmodws107 ~]$ mdstcl
TCL> @t.tcl 34
......... STUCK .........
```
if the process stays around it works repeatedly
```
[jas@cmodws107 ~]$ mdstcl
TCL> @t.tcl 35
TCL> @t.tcl 36
TCL> @t.tcl 37
TCL>
this is fine
so it only has a problem when it is a new process
```

Some more information:

1.  the treatment of the return values for send with  MSG_DONTWAIT do not seem to be being handled correctly. see: https://developer.ibm.com/tutorials/l-sockpit/
2. the case that the 2nd `send` in SendReply fails was not causing a retry
3. the print statement that the connection was lost was trashing the 1st and 3d terms of the IP address (the debugger showed them to be correct)
4. I don't think this is relevant but is the global variable that holds the list of client sockets thread safe ?

I am positing that AttachPort and RemoveClient in that c file are not working correctly.

I tried removing the DONTWAIT and checking for success on the 2nd Send.
This did not help.

Stopping for now.

**Comment by zack-vii** [comment]
hi josh,
 can you verify if the server_init action is a python program. also can you check if the first init finishes completly. the issue might be, that if you send a command via mdsip requesting a reply. the server will try to interrupt the task once the client disconnects. in case of a python program it will eventually mess up the python GIL which will cause a subsequent task to get stuck trting to acquire it. if you do not intend to stick around for the reply. can you check this by instead of exoting the first mdsip, putting ctrl+z it and bg it to a background process. alternatively, you could just wait for the task to finish before exit. does it still get stuck on the second try?

**Comment by zack-vii** [comment]
Hm, I gave it some thoughts but I am still confused with one oddity and parts of your statements.
The oddity:

$ cat t.tcl
set tree lh
create pulse 'P1'
set tree lh /shot = 'P1'
dispatch .HARDWARE.SEND_INIT
$

What is shot 'P1'? how does thos resolve to a int? is the P dropped? is it a variable name?

> Some more information:
> 1. the treatment of the return values for send with MSG_DONTWAIT do not seem to be being handled correctly. see: https://developer.ibm.com/tutorials/l-sockpit/<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.ibm.com%2Ftutorials%2Fl-sockpit%2F&data=02%7C01%7C%7Caef68c1ff5d747cbaec908d71c4604f1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637008959362712964&sdata=lrkaaUpJxZA4tAC3J9185IUP4%2FbEJ9k3OQ8U8gD6X5E%3D&reserved=0>

Why do you think that? The 1st client is dead. send() should eventually return an error if it died soon enough. It may pass if the sendbuffer is large enough and MSG_DONTWAIT is active as the error occurs async and is ignored. But that would be as if the client died just after receiving the reply.

> 2. the case that the 2nd send in SendReply fails was not causing a retry

Why would you want that? this should only happen if the client hangs up. or the connection breaks for other reasons.

> 3. the print statement that the connection was lost was trashing the 1st and 3d terms of the IP address (the debugger showed them to be correct)

trashing how? do you mean it showed up scrambled in terminal. this is because stdout is buffered but stderr is not, right?

**Comment by joshStillerman** [comment]
```
 hi josh,
 can you verify if the server_init action is a python program. also can you check if the first init finishes completly. the issue might be, that if you send a command via mdsip requesting a reply. the server will try to interrupt the task once the client disconnects. in case of a python program it will eventually mess up the python GIL which will cause a subsequent task to get stuck trting to acquire it. if you do not intend to stick around for the reply. can you check this by instead of exoting the first mdsip, putting ctrl+z it and bg it to a background process. alternatively, you could just wait for the task to finish before exit. does it still get stuck on the second try?
```
The thing being called is a TDI fun which writes a file.
It does complete
Waiting before exiting does not help

The behavior is seen if the client (doing the dispatch on the node) is TCL, Tree.Tcl, or Node.dispatch().  

The behavior is always fine if the dispatching program stays running.

**Comment by joshStillerman** [comment]
The 'P1' is the 1st argument to a TCL `@` command.
```
@t.tcl treename 42
```

t.tcl
```
set current 'P1' 'P2'
```

The garbled output from the server always looks like:
```
Thu Aug  8 15:35:24 2019: Dropped connection to 4294967238.125.4294967223.107:8903
```
where the client connecting is `198.125.183.107` . note the 125 and the 107 are rendered correctly.  As I said, I think this may be a compiler glitch as GDB show the correct values for the arguments to printf in SendReply.

Will conin ue with response on DONTWAIT in the next comment

**Comment by zack-vii** [comment]
The 'P1' is the 1st argument to a TCL @ command.

@t.tcl treename 42


t.tcl

set current 'P1' 'P2'

cool, I did not know that.

The garbled output from the server always looks like:

Thu Aug  8 15:35:24 2019: Dropped connection to 4294967238.125.4294967223.107:8903


where the client connecting is 198.125.183.107 . note the 125 and the 107 are rendered correctly. As I said, I think this may be a compiler glitch as GDB show the correct values for the arguments to printf in SendReply.

I likely cast the arg to signed char. so 198 becomes negative. the printf uses %u right so it is likely cast to int32_t before it is cast to unsigned. hence the int underflow. it is just a broken dbg line.

**Comment by joshStillerman** [comment]
So, on to the return values from send....
if DONTWAIT  is set, I think it works like:
1 - if it would have waited it returns -1 and errno contains ...
```
Enables nonblocking operation; if the operation would block,
              EAGAIN or EWOULDBLOCK is returned.
```
2 - it could return 0 - happy but no bytes
3 - It could return n < size .  - not all sent
4 - it could return n == size - all sent

The symptom is that server does not know that the record in the Client list is . no longer valid, and the logic that re-tries removes then retries is somehow not working.

If all the processes are on the same computer then it does the right thing

**Comment by joshStillerman** [comment]
Tried setting TCP KEEPALIVE to start at 1 sec and go every sec and fail on 1 non response.  No joy.

I think the right answer - and this is a non trivial change is to keep track of the response sockets in the code that accepts the original connections, and when those original connections break (I know we know when this is as messages are added to the logs) remove any Response Sockets for that host and port.

**Comment by zack-vii** [comment]
given that we should have responce ports available for each client and they are private to that client we could move the list of responce connections to the connection struct of the client. i once started a complete doover of mdsip. but it failed because it was not backwards compatible. maybe we should think of a better schema and move on to major version 8. in which we irgnore backward compatibility with older versions on mdsip level. it would probably only affect dispatching whereas reading data would still work as usual even with older clients.

**Comment by joshStillerman** [comment]
we can definitely talk about this in September. I am not opposed to 
making a major release which breaks connections to old mdsip clients.  
We should think about what else might go into that release.  In the 
meanwhile I need to get this working. Alternatives seem to be:

1 - fix it as written

2 - move the response connection info to the connection struct

3 - revert the code in SendReply to before it was broken.

Thoughts ?

**Comment by zack-vii** [comment]
by fix it as written you mean treat return -1 and errno == EWOULDBLOCK or errno == EAGAIN as return 0. If that fixes it lets go with it.

**Comment by zack-vii** [comment]
Well if we keep retrying on EWOULDBLOCK we could just remove the MSG_DONTWAIT

**Comment by joshStillerman** [comment]
I tried that it did not fix the problem

**Comment by zack-vii** [comment]
we should definitely add a test that covers the lockup. could you put one together. That would be useful to pin down the whats actually wrong with the code

**Comment by tfredian** [comment]
Adding a test might be a bit tricky. Apparently Josh discovered that the problem only occurred when the connection was made from another machine and local connections worked fine. It is conceivable that we could come up with some test scheme perhaps using two jenkins slaves on different machines but it would be somewhat complicated. The trigger job could start an mdsip action server that another job could communicate with. The sub job could contain a timeout and the trigger job could kill its action server when the sub jobs complete (successfully or not).

**Comment by zack-vii** [comment]
is there a chance the issue can be triggered when instead of localhost 127.0.0.1, the test would connect to 0.0.0.0 or its actual ip. i did not have had the time yet to set up a configuration myself. maybe I am able to set something up tonight, once maya is asleep.

**Comment by tfredian** [comment]
I don't know the details of the case where this problem surfaced but I suspect it occurred when an action (which probably had the hostname of the action server in the action) was dispatched so it likely resulted in using the actual ip address when dispatched from either another host or the host where the action server was running. I think if Josh can't find an obvious fix he'll try to put together some simple scripts which demonstrate the problem.

**Comment by joshStillerman** [comment]
The plot thickens: 
1. When SendReply tries to write 60 bytes to a socket that used to be connected to  process that has gone away, the first time it 'works' - gets back 60.  The second time it tries to use that socket it gets an error.
2. removing DONTWAIT does not change the behavior
3.  adding a 1 second TCP heartbeat does not change the behavior
4. someone (https://www.softlab.ntua.gr/facilities/documentation/unix/unix-socket-faq/unix-socket-faq-2.html) said ` It is less clear what happens to write() calls in this case; I would expect EPIPE, not on the next call, but the one after.`

Here is a script that demonstrates the problem:
```
#!/bin/bash
export s_test_path=/tmp
cat - > /tmp/mdsip.hosts <<EOF
*@* | nobody
EOF
mdstcl <<EOF
edit /new s_test
add node act /usage=action
write
close
set tree s_test
put act "Build_Action(Build_Dispatch(2, 'localhost:9999', 'INIT', 50, *),  1, *, *, *)"
EOF
mdsip -s -p 9999 -h /tmp/mdsip.hosts &
cat -> /tmp/s_test.tcl <<EOF
set tree s_test
dispatch act
exit
EOF
echo "try a dispatch"
mdstcl @/tmp/s_test.tcl
echo "try a second time"
mdstcl @/tmp/s_test.tcl
echo "all done"
```

**Comment by tfredian** [comment]
There are several issues at play here most of which are being caused by the unusual use case (if this is how this is being used to dispatch actions). I wouldn't be surprised if this problem existed in the past but since actions tended to be dispatched by a long running process the situation never occurred. The problem is that the action server is not detecting that the client has exited and the socket in its client list is no longer valid. Surprisingly when the action server sends a reply on that socket (created when the previous client process dispatched an action) it doesn't detect an error and the client never receives that reply. Adding to the confusion is the use of random() to pick a port to communicate on. The random() function produces the same sequence of values every time a process starts up so the mdstcl process picks exactly the same port each time it runs and since the action server already had a client in its list with the same ip address and port it tries to use the same socket.

I think we need to add a check that works on the server side to ensure the socket in the client list is still valid. I'll do some more investigation to see if there is a reliable way to do this. It would probably be a good idea for the server side to periodically check all the sockets in its client list and close the socket and remove the clients if the socket is invalid.

If this practice of run mdstcl to dispatch a single action is needed perhaps a simple short term workaround would be to have the client connect to a long running mdsip server and evaluate and expression that opens the tree and issues the tcl command so that this mdsip server will establish the reply connection with the action server and retain it.

**Comment by zack-vii** [comment]
But on the other hand if the client disconnected/died. should send reply not just try to send the reply and only remove the reply socket if it fails but otherwise return without error. th next dispatch should get its own personal replyport which is unaffected by the removal of the first one.

**Comment by tfredian** [comment]
The problem was that the send reply code was succeeding even though the client had already exited. It turns out that send to the disconnected socket behaves like a connected one and only fails if you do two sends to the socket. Breaking the send into two 30 byte packets detects the bad socket and triggers the reconnect. It all seems to be working now.

 If you decide to refactor the dispatcher mdsip code again you should explore a way to find and clean disconnected clients otherwise there is a possibility the client list could retain many broken sockets unless the client connects again and uses the same reply port (which is somewhat likely since random() produces the same list of ports every time). I played with using various combinations of select etc on the server side client sockets but the only way we could detect the disconnect is by doing two sends to the socket. Anyway, this issue is closed for now...
