### ISSUE TITLE
version in installed package

### ISSUE THREAD

**Issue by drsmith48** [MDSplus/mdsplus#1869]
Where can a user find the version of MDSplus in an MDSplus installation?  What methods exist for revealing the version?

**Comment by zack-vii** [comment]
e.g. you can start mdsdcl and use show version
```
mdsdcl> show version
```

**Comment by drsmith48** [comment]
This works on the newer MDSplus version installed locally on my Mac, but it doesn't work on the older version on the PPPL cluster.  Are there methods for older MDSplus versions?

**Comment by zack-vii** [comment]
How old ate we talking about? is this a linux machine. Would it not be easiest to ask you packet manager? Otherwise I assume the creation date of the lib will give you a clue. Or you may finde a Changelog file in the installation folder with infos about the git hash that was merged last.
What specific detail are you interested in. Maybe its easier to probe for specific features instead.

**Comment by zack-vii** [comment]
We may want to add a section to debug information in our wiki. this 'How to detect the version of ...' could find a place there.

**Comment by zack-vii** [comment]
http://www.mdsplus.org/index.php/Documentation:FAQ#What_version_am_I_currently_running.3F
