### ISSUE TITLE
separate jobs for each of the sanitizers

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2195]
Create separate jobs for each of the sanitizers.  Like:
`Ubuntu18-sanitize-address`
They don't need to do the release stuff but do need to run the sanitizer.

**Comment by joshStillerman** [comment]
sanitize address fails badly on UB18.  Some of the complaints seem to be pure python stuff, others may be in our code.  Moved it to where it was (FC23) to confirm that it is not just a question of settings.

**Comment by joshStillerman** [comment]
works on fc23, fails on UB18 and UB16. python versions not very different.  Compiler versions may be more so.

**Comment by zack-vii** [comment]
tge python suppressions are tailored for the fc23 version. this is why it is tedious to move the tests as the python or java version is usually different resulting in false positives as tge 'broken' code is not in code we manage but python/java

**Comment by joshStillerman** [comment]
FC30 also fails - but on less things.

**Comment by joshStillerman** [comment]
FC28 also fails

**Comment by joshStillerman** [comment]
Timo -
  I did not realize how tailored it was.  Is this true of the other sanitization / valgrind jobs ? 

Some of the jobs have logic for do-release.  others do not.  Is the way to deprecate platforms we are using for tests to remove the release from the job ?

**Comment by zack-vii** [comment]
well it makes sense to run those tools on a modern machine, assuming they have improved. however that takes a little time to tailor them for the new python and java release. that is:
1. running the test on the new targets.
2. determine which finds are due to third party code
3. add third party suppressions
4. fix new finds due to improvements of the tools

this should be done possibly locally with docker. we may want to promote alpha to stable once dine so we dont have to do it twice... for now we could only disable targets that have no special tool assigned in pull-request. we dont necessarely test again for releases as we only merge source code changes through pull requests anyway. so in principle, the release branches should have been tested already.

**Comment by joshStillerman** [comment]
The current plan is:
1 - put the jenkins config in git. (Stephen is working on this)
2 - disable the deprecated platforms that are not doing special checks
3 - disable the release part of deprecated platforms that are doing special checks
4 - Do as Timo suggests above

**Comment by joshStillerman** [comment]
Jenkins now in MIT github

I have removed fc17-28 from the releases
and fc17-23 from the tests (the fc23 test is done by a job called ub18-xxx - which is actually running fc23 for now

**Comment by zack-vii** [comment]
how about making jobs like test-asan, test-ubsan, test-tsan, test-memcheck, and test-helgrind. instead which will only run the tests. the os does not have to be part of the job as we may want to update it without changing too many jenkins settings. ideally even we would have the job description in the repo.. e.g. we could put it in the deploy/os folder.

deploy/build --os=test-asan

could run the address-sanitizer for the designed docker matching the suppression files.

**Comment by zack-vii** [comment]
solved for alpha in #2202

**Comment by zack-vii** [comment]
attempt to solve it quickly for stable failed #2208

**Comment by zack-vii** [comment]
alpha and stable have test-* tool dedicated jobs. currently all tools are running under fc32.
