### ISSUE TITLE
could anybody give me a tutorial to teach me how to use c++ interface of mdsplus in vs, pleaase help me

### ISSUE THREAD

**Issue by hunter-asd** [MDSplus/mdsplus#2277]

**Comment by zack-vii** [comment]
Hi there,
I am not sure how up-to-date this is but until @GabrieleManduchi can help you you may want to check out 
https://www.mdsplus.org/index.php?title=Documentation:Tutorial:MdsObjects
and maybe narrow down your issue.

Hope this helps a bit

**Comment by joshStillerman** [comment]
Can one of you @AndreaRigoni @GabrieleManduchi @kgerickson help him with this ?

**Comment by kgerickson** [comment]
I can help.  One thing you will have to take great care in is understanding
which API returns a "new" object and which does not.  It is extremely
important to properly manage memory here.  I recommend using wrapper
objects to handle it with RAII.  It's a little too complicated to use
c++11's smart pointers, because you can't just call delete in all cases.

That said, have you gone through the examples here?

https://mdsplus.org/index.php?title=Documentation:Tutorial:MdsObjects&open=1625331108715982618623&page=Tutorials%2FAPIs%2FC%2B%2B

That should get you started.  Do you have specific questions arising from
going through that tutorial?

-- 
Keith Erickson
Cell: 609-455-2618 (preferred)
Office: 609-243-3064
