### ISSUE TITLE
python: after getting active tree with MDSplus.Tree(), setDefault() fails: "TreeNode must be in same tree"

### ISSUE THREAD

**Issue by cenkoloji** [MDSplus/mdsplus#2325]
version: mdsplus-stable (7.96-17)

I'm not sure if this is a bug, or I'm not following correct practice. In my setup, I call a python function from tdi. In python, if I get handle of the active tree with MDSplus.Tree(), I can't use setDefault().

To reproduce failure:
```
TreeOpen("my_tree",-1)
py("import MDSplus; t=MDSplus.Tree(); print(t); t.setDefault(t.getNode('\\TOP.TXT'))")
```

output: 
```
Tree("MY_TREE",-1,"Normal")
Traceback (most recent call last):
  File "/usr/local/mdsplus/tdi/python/Py.py", line 58, in Py
    exec(compile(cmds,'<string>','exec'),env,env)
  File "<string>", line 1, in <module>
  File "/usr/local/mdsplus/python/MDSplus/tree.py", line 954, in setDefault
    raise TypeError('TreeNode must be in same tree')
TypeError: TreeNode must be in same tree
0
```
I tracked it down to:  [/tree.py#L1050](https://github.com/MDSplus/mdsplus/blob/68cba11e7ca48b0990eea9714273bba714f7878b/python/MDSplus/tree.py#L1050) :
```
if not node.ctx == self.ctx:
    raise TypeError('TreeNode must be in same tree')
```

I even printed out, and the both c_void_p object has same value:
```
TDI> py("import MDSplus;t=MDSplus.Tree();print(t.ctx);print(t.getNode('\\TOP.TXT').ctx)")
c_void_p(94186050127232)
c_void_p(94186050127232)
```

This problem is ONLY occuring if I use Tree() to get the active tree already opened in TDI. Following works fine:
```
TreeOpen("my_tree",-1)
py("import MDSplus; t=MDSplus.Tree('my_tree',-1); print(t); t.setDefault(t.getNode('\\TOP'))")
```

**Comment by zack-vii** [comment]
hmm may be that ctypes.c_void_p does not compare the target address, could you try changing the comparing line to use ctx.value instead.. if that solves your issue, please make a pull request =)

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Cenk Yildiz ***@***.***>
Sent: Friday, June 18, 2021 11:10:53 AM
To: MDSplus/mdsplus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MDSplus/mdsplus] python: after getting active tree with MDSplus.Tree(), setDefault() fails: "TreeNode must be in same tree" (#2325)


version: mdsplus-stable (7.96-17)

I'm not sure if this is a bug, or I'm not following correct practice. In my setup, I call a python function from tdi. In python, if I get handle of the active tree with MDSplus.Tree(), I can't use setDefault().

To reproduce failure:

TreeOpen("my_tree",-1)
py("import MDSplus; t=MDSplus.Tree(); print(t); t.setDefault(t.getNode('\\TOP.TXT'))")


output:

Tree("MY_TREE",-1,"Normal")
Traceback (most recent call last):
  File "/usr/local/mdsplus/tdi/python/Py.py", line 58, in Py
    exec(compile(cmds,'<string>','exec'),env,env)
  File "<string>", line 1, in <module>
  File "/usr/local/mdsplus/python/MDSplus/tree.py", line 954, in setDefault
    raise TypeError('TreeNode must be in same tree')
TypeError: TreeNode must be in same tree
0


I tracked it down to: /tree.py#L1050<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMDSplus%2Fmdsplus%2Fblob%2F68cba11e7ca48b0990eea9714273bba714f7878b%2Fpython%2FMDSplus%2Ftree.py%23L1050&data=04%7C01%7C%7C698f4533c3b8480102c308d93238f9b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637596042548712937%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wEzgDB6xSWdWOo9df0AXDxMu4furmTiyrIpdYfO6JEE%3D&reserved=0> :

if not node.ctx == self.ctx:
    raise TypeError('TreeNode must be in same tree')


I even printed out, and the both c_void_p object has same value:

TDI> py("import MDSplus;t=MDSplus.Tree();print(t.ctx);print(t.getNode('\\TOP.TXT').ctx)")
c_void_p(94186050127232)
c_void_p(94186050127232)


This problem is ONLY occuring if I use Tree() to get the active tree already opened in TDI. Following works fine:

TreeOpen("my_tree",-1)
py("import MDSplus; t=MDSplus.Tree('my_tree',-1); print(t); t.setDefault(t.getNode('\\TOP'))")

**Comment by cenkoloji** [comment]
Indeed, this solves the issue. I'll take care of it.

**Comment by zack-vii** [comment]
Thanks =)

**Comment by cenkoloji** [comment]
Some quick questions:
- Do I need to make a pull request for both alpha and stable branches?
- Once this change is pushed into stable, how long does it take to propagate to mdsplus dnf repository for RHEL? (Is it done automatically?)

Thanks

**Comment by zack-vii** [comment]
You can push it to alpha only.. we will review it and merge it.. after merge it will usually be release the next day. 

Since its is a bug fix we will apply the fix to stable as well. and make a new release over night
