### ISSUE TITLE
stable version dependency failure

### ISSUE THREAD

**Issue by kgerickson** [MDSplus/mdsplus#2337]
While updating from 7.96-17 to 7.131-3 to pick up a different fix, I get a dependency error due to the specification of requiring python-numpy on EL7.

The old version had the following deps:
```
$ rpm -qR mdsplus-python
/bin/sh
/bin/sh
/usr/bin/env
mdsplus-kernel = 7.96-17.el7
numpy
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1

```
The new one has the following:
```
$ yum deplist mdsplus-python
Loaded plugins: auto-update-debuginfo, changelog, fastestmirror, langpacks, merge-conf, remove-with-leaves, show-leaves, verify
package: mdsplus-python.noarch 7.131-3.el7
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-34.el7
  dependency: /usr/bin/env
   provider: coreutils.x86_64 8.22-24.el7_9.2
  dependency: mdsplus-kernel = 7.131-3.el7
   provider: mdsplus-kernel.noarch 7.131-3.el7
  dependency: python-numpy
   Unsatisfied dependency
```

The key difference is that the old one depended on "numpy", while the new one depends on "python-numpy".  The former is correct for EL7.  An alternative is to specify "python2-numpy" instead, if it's python2 version that's required.

Note that this is IMO either 1) a misconfiguration on my side, or 2) a critical limitation regression in the stable branch.  I'm hoping it's (1) :)

**Comment by zack-vii** [comment]
hmm that should be then numpy it seems.. there was something with the packaging. a few weeks back.. i will check by monday

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: kgerickson ***@***.***>
Sent: Friday, July 2, 2021 11:31:02 PM
To: MDSplus/mdsplus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MDSplus/mdsplus] stable version dependency failure (#2337)


While updating from 7.96-17 to 7.131-3 to pick up a different fix, I get a dependency error due to the specification of requiring python-numpy on EL7.

The old version had the following deps:

$ rpm -qR mdsplus-python
/bin/sh
/bin/sh
/usr/bin/env
mdsplus-kernel = 7.96-17.el7
numpy
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1



The new one has the following:

$ yum deplist mdsplus-python
Loaded plugins: auto-update-debuginfo, changelog, fastestmirror, langpacks, merge-conf, remove-with-leaves, show-leaves, verify
package: mdsplus-python.noarch 7.131-3.el7
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-34.el7
  dependency: /usr/bin/env
   provider: coreutils.x86_64 8.22-24.el7_9.2
  dependency: mdsplus-kernel = 7.131-3.el7
   provider: mdsplus-kernel.noarch 7.131-3.el7
  dependency: python-numpy
   Unsatisfied dependency


The key difference is that the old one depended on "numpy", while the new one depends on "python-numpy". The former is correct for EL7. An alternative is to specify "python2-numpy" instead, if it's python2 version that's required.

Note that this is IMO either 1) a misconfiguration on my side, or 2) a critical limitation regression in the stable branch. I'm hoping it's (1) :)

**Comment by kgerickson** [comment]
Any luck?

**Comment by zack-vii** [comment]
i think this would do it : branch zck-numpy-packaging
but could not test it yet
