### ISSUE TITLE
How to get size of array in numeric MDS node from length

### ISSUE THREAD

**Issue by cenkoloji** [MDSplus/mdsplus#2431]
Hello,

I see that  `getnci("NODE","LENGTH")` is much faster then getting the array and reading the size, that's why we use this on numeric nodes.

However, I don't see a consistent way to get array size from the LENGTH. For an array of 2-byte words, I empirically see that: `LENGTH = 2*NELEMENTS + X`

This number X depends on how data is put on the tree.
* If I send data from a d-tacq device, `X = 40`
* If I put data (just with TreePut or via python interface), `X = 32`

Is there a way to get the value of X, so I can deduce the array size? If not, is there another efficient way to do this?

Here's an example, I have 2 nodes, filled in different ways, with exactly same data. I can't find any difference, though "length" is different.
```
TDI> TreeOpen("raw_dttest",37);

TDI> size(MODULE001:CHANNEL_001)
1200
TDI> size(MODULE001:CHANNEL_002)
1200

TDI> getnci("MODULE001:CHANNEL_00"//["1","2"], "LENGTH")
Long_Unsigned([2440LU,2432LU])

TDI> getnci("MODULE001:CHANNEL_00"//["1","2"], "DTYPE")
Byte_Unsigned([7,7])

TDI> getnci("MODULE001:CHANNEL_00"//["1","2"], "CLASS")
Byte_Unsigned([195,195])
```

**Comment by zack-vii** [comment]
Hm well to consistently get the array size from length is simply not necessarily possible. 

also please compare RLENGTH and LENGTH. 
You may be safe and it ist the other way round but i think LENGTH is simply the number of bytes the data occupies in the datafile, which may be smaller because of compression whereas RLENGTH is the number bytes in the record, what you are after.

the class of the record may be an array but there are different kinds of arrays. simple array bounded arrays etc .. and one more. they descriptors of different size.

MDSplus data is presented by descriptors which hold item length, dtype, and class + additional fields based on class + additional fields based on class properties. You see, to determine the overhead of the descriptor part you need knowledge of the content.

Once you know that you could determine the offset X by calculating the difference of LENGTH and ITEMSIZE*SAMPLES. which should be consistent given the data has the same format.

once you data is more complex (e.g. a signal or with_units etc.) it is even worse. 

PS: usually reading the data form a local source is pretty fast.. so sometimes it makes sense to use the thin client  to get meta information. 
e.g.: python  (untested, from the top of my head)
```python
server = 'my-mdsplus-server'
expt = 'my_tree'
shot = 7357
nodepath = 'PATH.TO:NODE'

import MDSplus
con = MDSplus.Connection(server)
con.treeOpen(expt, shot)
shape = con.get("SHAPE($)", nodepath)
```

**Comment by zack-vii** [comment]
For a better understanding as X is only up to 40 bytes.
can you do a tdi
```tdi
serializeout(`getnci('record', MODULE001:CHANNEL_001))[0:40]
serializeout(`getnci('record', MODULE001:CHANNEL_002))[0:40]
```

**Comment by cenkoloji** [comment]
Thanks Timo, I did try to use `shape()`. But the speed is really not comparable, it explodes easily with large arrays and large number of channels. If there is no way to do this with LENGTH I may end up going back to using that.

The serializeout indeed shows different arrays, and I see some hints of the descriptor size (I aligned them for convenience)

```
serializeout(`getnci('MODULE001:CHANNEL_001','RECORD'))[0:40]
serializeout(`getnci('MODULE001:CHANNEL_002','RECORD'))[0:32]

Byte_Unsigned([2,0,7,195,24,0,0,0,0,0,112,1,96,9,0,0,0,0,0,0,176,4,0,0,2,0,199,194,28,0,0,0,4,0,0,0,0,0,0,0,0])
Byte_Unsigned([2,0,7,195,16,0,0,0,0,0,0  ,1,96,9                  ,0,0,2,0,199,194,28,0,0,0,4,0,0,0,0,0,0,0,0])
```

The 5th element is 24 vs 16. The difference 8 is exactly the difference in number of bytes in 2 descriptors. Though - not sure what to make of it.

**Comment by zack-vii** [comment]
ah hmm i truied to deserialize which did not work.. turns out class 195 is actually a DESCRIPTOR_CA where th C in CA stands for compressed. 
```
2, 0,    is the lengh of you item i.e. word := 2
7,       is dtype WORD
195,     is actually compressed array (please verify RLENGTH vs. LENGTH)
24,0,0,0 is the offset to the payload of CA
0,0,
112,    are flags?
1,        number of dimensions?
96,9,     is 0x0960 = 2400 the number of bytes of the decompressed blob
0,0,    not sure
0,0,0,0, not sure but due to flags
176,4,0,0, is num_samples 0x04b0 = 1200
2,0,199,194, is actually a function (class=194) call (dtype=199), of type 2 (not sure this controls) to possibly the decompress method

As you can see.. it is quite complex

**Comment by cenkoloji** [comment]
Complex indeed. Thanks for the help. I don't think there is a way to do what I want.
