### ISSUE TITLE
Add Tag with LabVIEW

### ISSUE THREAD

**Issue by gronchi** [MDSplus/mdsplus#2455]
Is there a way to add tags to nodes using LabVIEW? There are the 'tree find tags.vi' and 'tree remove tag.vi' in the LabVIEW library, but I couldn't find a way to add tags to nodes.

**Comment by joshStillerman** [comment]
I do not think the Labview API supports any Tree Editing operations of which add_tag is one.  In general you should not be editing the tree in the course of day to day operations.  Tree edits should be done on the model, or well after the fact to ammend previous shots.  This is because they require exclusive access to the tree.

Where are you from/working?  Feel free to join the MDSplus discord: 

https://discord.gg/4gt6RbhHDm <https://discord.gg/4gt6RbhHDm>

-Josh

**Comment by gronchi** [comment]
It actually supports tree editing: you can build an entire tree with substructures and nodes from scratch in LabVIEW by using "Tree Create (Mode)", "Tree Add Node" and "Tree Set Default".  But I totally agree that it's better to use a prebuilt model tree during operations instead of creating it on the fly in LabVIEW.

**Comment by joshStillerman** [comment]
Please use other tools for tree edititng

In general, you do not want to edit the trees on the fly in a multiuser environment
