### ISSUE TITLE
[Matlab] Cannot read an array of strings using mdsvalue

### ISSUE THREAD

**Issue by lvovskiy** [MDSplus/mdsplus#2456]
Hello,

when I try to access the node containing an array of strings using mdsvalue in Matlab, I get this error:

'Java exception occurred: 
     MDSplus.MdsException: Unexpected returned data type in mdsip connection
     	at MDSplus.Connection.get(Native Method)
     	at MDSplus.Connection.get(Connection.java:61)
     	at MDSplus.Connection.get(Connection.java:66)'

In IDL or Python I can get it totally fine, but not in Matlab.

I use Matlab 2019b and mdsplus-stable_release-7-96-9 installed at D3D.

**Comment by santorofer** [comment]
Hello Ivovskiy,

I'm not able to reproduce your problem. I have a test node with an array of strings, but the Matlab MDSplus API seems to be working fine for me.
Could you give me an example of the settings that you have, so that I can reproduce your issue? E.g how did you created the node, and the Matlab calls that you used?

Thank you,
Fernando

**Comment by joshStillerman** [comment]
Fernando did you test it with the java matlab API or with the python one ?

**Comment by santorofer** [comment]
Hi Josh, I tested it with (java) Matlab API.

F

**Comment by santorofer** [comment]
We were able to reproduce the issue.

It seems that Matlab cannot currently handle types like `MDSplus.List`, I would recommend using the `MDSplus.StringArray` type instead.

You can set this from Python like so:

```py
tree.NODE.record = MDSplus.StringArray( your data here )
```

If you have any issues, let us know.
