### ISSUE TITLE
Configuration of  mdsip server for TCP/IP-based events transferred among subnetworks

### ISSUE THREAD

**Issue by wbb12** [MDSplus/mdsplus#2542]
I try to send mdsevent across  subnetworks. From the [wiki](https://www.mdsplus.org/index.php/Documentation:Tutorial:Events), I set the define env variable mds_event_server in Python as the mdsip address, and the event object returns an error.
```
from MDSplus import Event
import os
os.environ['mds_event_server'] = '10.78.2.113'
os.environ.pop('UDP_EVENTS')
class MyEvent(Event):
    def run(self):
            print("RECEIVED EVENT " + self.getName())
            print(self.getTime())
            print(self.getRaw())

eventObj=MyEvent('test_event')
#ConnectToMds_: Success
#Error connecting to 10.78.2.113>>> 
```
The MDSplus server has no extra configuration except the tree path. So how to configure the server to support the event to transfer the event based on TCP/IP?

If the mds_event_server env is not defined in the script, the eventObj can receive the event from other machines which send the event in the same subnet. 

Another question is that the Jscope doesn't update the data,  even if the jscope is in the same subnet.

**Comment by GabrieleManduchi** [comment]
There were several issues related to this topic:
1) there was a mismatch in the WIKI documentation. It has been corrected now
2) The mdsip-based event communication was broken due to the changes done some time ago to the management of static information in mdsip. A PR has been issued (#2543) with the required fixes.
