### ISSUE TITLE
MDSplus Python package is not installable by easy_install

### ISSUE THREAD

**Issue by wagdav** [MDSplus/mdsplus#278]
Based on the documentation the Python bindings should be installable by executing:

```
easy_install MDSplus
```

This used to be the case, but since the end of December 2015 this is not working anymore. Example:

```
$ easy_install MDSplus
Searching for MDSplus
Reading https://pypi.python.org/simple/MDSplus/
No local packages or download links found for MDSplus
error: Could not find suitable distribution for Requirement.parse('MDSplus')
```

**Comment by tfredian** [comment]
Hi David,

```
 Thanks for the report. I hope to resolve this issue as soon as 
```

possible. I suspect there is some incompatibility with the information 
stored in the MDSplus packages and how the pypi.python.org is inspecting 
the packages. I'm not certain at this point whether this was caused by a 
change of the MDSplus packages or a change in the python package index 
service.

Cheers,
Tom

**Comment by wagdav** [comment]
Hi Tom,

It works again. Is it possible that autobuilder failed somewhere around Christmas and the eggs were not properly published?

Cheers,
david

**Comment by tfredian** [comment]
Hi David,

```
 I don't think so. As far as I can tell they must have changed the 
```

python package index used by easy_install. It used to work if the module 
description on the package index provided a url to a page that listed 
all the versions of the particular module. That nolonger seemed to work. 
Instead of configuring it with a url I manually uploaded the MDSplus 
python eggs directly to the package index and that worked. I will still 
need to change the autobuilder to post new MDSplus python modules 
directly to the index. Thanks for letting me know there was a problem.

Cheers,
Tom

**Comment by tfredian** [comment]
We are now uploading the MDSplus python packages to the python package index so easy install should now be working again. I would be cautious of using easy_install though as it will pick up the lastest version which may or may not be compatible with the version of MDSplus you may have installed. If you install MDSplus using an installer or from an MDSplus repository then it normally comes with an mdsobjjects/python directory which contains the MDSplus python module compatible with that release. You can use that by cd'ing to that directory and doing "python setup.py install" running the version of python you want to install the MDSplus package into.

**Comment by smithsp** [comment]
I am seeing this problem now.

**Comment by tfredian** [comment]
We have removed the MDSplus package from pypi so easy_install will no longer work. There have been too many issues when using pip or easy_install to install MDSplus from pypi since it often causes the python package installed to be incompatible with the version of the MDSplus software installed on the system. The recommended way to install the MDSplus python module is to use either one of the following:

pip install [-user] $MDSPLUS_DIR/mdsobjects/python

or

cd $MDSPLUS_DIR/mdsobjects/python
python setup.py install

**Comment by smithsp** [comment]
I found this reported on bugzilla with the similar comment http://www.mdsplus.org/bugzilla/show_bug.cgi?id=444#c1
Thanks for your response.

**Comment by eldond** [comment]
The path that contains `setup.py` is now `$MDSPLUS_DIR/python/MDSplus/` (for MDSplus verison 7.96.12), but otherwise `python3 setup.py install` worked.
