### ISSUE TITLE
The python quantity None is not properly handled when stored to an MDSplus node

### ISSUE THREAD

**Issue by jdelder** [MDSplus/mdsplus#373]
None is a valid python data value indicating that no specific value (other than None) has been assigned to a variable but the variable name has been created, exists and can be manipulated in code. The workaround is to choose default values like '' or -1 or similar magic values for variables that may or may not receive input or be assigned to at some point in the code. The ability to store some placeholder for None in MDSplus could result in cleaner code. 

---

The python built-in class/value None is not handled properly when stored to an MDSplus tree node. 

---

If the python value None is stored to a tree node by itself (use=ANY) then MDSplus throws an exception indicating that the node is empty. 

> > > a=st.getNode('SIGNAL4')
> > > a.putData('Test')
> > > print a.getData()
> > > Test
> > > c= None
> > > a.putData(None)
> > > print a.getData()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/sw/python/python2.6/lib/python2.6/site-packages/MDSplus/treenode.py", line 475, in getData
> > >     return TreeGetRecord(self)
> > >   File "/sw/python/python2.6/lib/python2.6/site-packages/MDSplus/_treeshr.py", line 220, in TreeGetRecord
> > >     raise TreeNoDataException("No data stored in node %s" % (str(n),))
> > > MDSplus._treeshr.TreeNoDataException: No data stored in node \OEDGE::TOP:SIGNAL4

---

If the Python None value is part of a list that is stored to a tree node then MDSplus throws an exception indicating that the data is corrupted. 

> > > c=[5.0,'test',8.0,None]
> > > print c
> > > [5.0, 'test', 8.0, None]
> > > d='Test'
> > > a.putData(d)
> > > print a.getData()
> > > Test
> > > a.putData(c)
> > > print a.getData()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/sw/python/python2.6/lib/python2.6/site-packages/MDSplus/treenode.py", line 475, in getData
> > >     return TreeGetRecord(self)
> > >   File "/sw/python/python2.6/lib/python2.6/site-packages/MDSplus/_treeshr.py", line 222, in TreeGetRecord
> > >     raise TreeException(MdsGetMsg(status))
> > > MDSplus._treeshr.TreeException: %TREE-E-TreeBADRECORD, Data corrupted: cannot read record

**Comment by tfredian** [comment]
Interesting. I understand that the getData() raises a TreeNoData exception. There has been some debate on whether or not this is the desired behavior or not. The main reason it is there is because the getData() raises exceptions for any failure status it receives when reading in data and when you store None it essentially erases the contents of the node and reading from an empty node returns an error status of NoData. Unfortunately many user applications now rely on this exception to signify no data and changing the behavior now could break those applications. It may be possible to add a function to the package to select the behavior for this. We'll certainly consider it.

The other BADRECORD problem is definitely a bug that we will investigate. There must have been a change to prevent this from happening because I don't get this behavior with the current alpha branch. It still doesn't work properly but instead of returning the list it now just returns an MDsplus EmptyData data type which is definitely wrong. The store of the list with a None in it is stored properly though and can be see with the DECOMPILE nodename command in mdstcl. We'll try to fix this problem.

**Comment by jdelder** [comment]
I was wondering if the value of None should be distinguished from an 
empty node containing no data - since None is actually a value. Unless 
folks have actually used None specifically to intentionally erase nodes 
rather than some other routine to return it to an unassigned state in 
which case there aren't many options.

On 2/25/2016 2:04 PM, Tom Fredian wrote:

> Interesting. I understand that the getData() raises a TreeNoData 
> exception. There has been some debate on whether or not this is the 
> desired behavior or not. The main reason it is there is because the 
> getData() raises exceptions for any failure status it receives when 
> reading in data and when you store None it essentially erases the 
> contents of the node and reading from an empty node returns an error 
> status of NoData. Unfortunately many user applications now rely on 
> this exception to signify no data and changing the behavior now could 
> break those applications. It may be possible to add a function to the 
> package to select the behavior for this. We'll certainly consider it.
> 
> The other BADRECORD problem is definitely a bug that we will 
> investigate. There must have been a change to prevent this from 
> happening because I don't get this behavior with the current alpha 
> branch. It still doesn't work properly but instead of returning the 
> list it now just returns an MDsplus EmptyData data type which is 
> definitely wrong. The store of the list with a None in it is stored 
> properly though and can be see with the DECOMPILE nodename command in 
> mdstcl. We'll try to fix this problem.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/issues/373#issuecomment-188933164.

## 

David Elder                             University of Toronto
david@starfire.utias.utoronto.ca        Institute for Aerospace Studies
Tel: 416-667-7891 or 905-839-8180       Fusion Research Group
Fax: 416-667-7799

**Comment by tfredian** [comment]
This should be partially fixed with https://github.com/MDSplus/mdsplus/pull/378 . The use of None in lists should now work.

**Comment by tfredian** [comment]
Sorry for taking so long to follow up with this but unfortunately it is currently impossible to store None (or an EmptyData) instance in a node in a tree as that is the mechanism for emptying the node of all data. A possible workaround might be to store some other special data type to indicate that empty data was stored into the node which would distinguish it from indicating that no data was written to the node. For most node usage types you could store an empty Opaque() instance:

node.record=MDSplus.Opaque()

Then applications could check for this type of data in the node.

This is not as elegant as you might hope but it should work. At this point changing the behavior of storing None in a node in a tree would likely break too many existing applications. It should be possible to add some features to the python module to hide this somewhat. One could imaging having
node.record=None storing an Opaque() instance and also adding code so comparing and empty Opaque instance with None return True so the following would behave similar to what your were hoping for:

node.record=None ## stores an Opaque() instance
node.record == None reports True when node.record is an empty Opaque instance.

We will discuss this option and if it seems like a generally useful feature we can add it to the python module. Since this is the first time we've heard of a need for this feature is would be unlikely we would want to extend this change to all the other language API's though.

**Comment by zack-vii** [comment]
turns out this is already supported in a way. you can store $MISSING (or python's d.MISSING()) in a node.
both python and tdi will render the node content to * or None, respectively. The node usage need to accept this though. I currently only tried ANY.

**Comment by tfredian** [comment]
Ok I think problem is solved. The following works:

NONE=dMISSING()

node.record=NONE
node.record==None produces a True result where if the node was empty it would throw an TreeNODATA exception.
