### ISSUE TITLE
data is cleared when node is deleted but changes are not written to tree

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#561]
the record should be updated during the write operating. However, it seems to be cleared already during TreeShr->TreeDeleteNodeExecute()

**Comment by tfredian** [comment]
This is a bit tricky to deal with. We could easily avoid initializing the node characteristics of a deleted node but we would also need to avoid changing the node characteristics of that nid if a new node is added which reuses the deleted node id. This would require keeping a copy of the entire characteristics file in memory and make all changes during edit sessions there instead of in the file. Another solution might be to keep a table of edited nids and read/write nci info to a memory buffer instead of the file and only write the nci info of all edited nids during the write operation. Either solution is possible but non-trivial. We'll have to decide if such a fix is worth the effort.

**Comment by zack-vii** [comment]
could one not prevent new nodes to reuse node ids of nodes that have been removed and not yet committed by "write". Could one just remove their relationship to their parents. This way they would not show up in listings but remain existent to the database. During the write method the orphaned could then be removed safely from the registers.

**Comment by tfredian** [comment]
This is a possibility but quite complicated. During the edit process when a node is deleted it could be unlinked from the node hierarchy and placed on a deleted list in memory. During the write operation any nodes on the deleted list would then have their characteristics erased and only then be moved to the free list pool. I can see how difficult this might be to implement. I agree this would be an improvement but there is a question of return on investment since this has been the behavior for over twenty years without any complaints from the user community.

**Comment by tfredian** [comment]
Addressed by https://github.com/MDSplus/mdsplus/pull/578
