### ISSUE TITLE
Some MDSIP C++ classes and functions should take const char*

### ISSUE THREAD

**Issue by jacklovell** [MDSplus/mdsplus#782]
Some MDSplus C++ classes take char* as an argument. For example, Connection() takes the server IP address as char*, and Connection::openTree() takes the tree name as char*. However, these arguments are not modified during the function and so could be made const char*.

This would then allow the arguments to be given using std::string::c_str() rather than having to deal with C-style char arrays in user code. They could even be string literals, which are useful for simple codes at e.g. JET which only need to deal with one MDS server and maybe even only one tree. Currently, using either of these methods with -Wall produces warnings about passing constant arrays as a non-constant function parameter.

**Comment by kgerickson** [comment]
Yes, ideally everything should be const-correct.  The problem here is that changing this will be an ABI change, breaking backwards compatibility (and at the very least requiring a soname bump).  Further, most of these pointers get passed down to lower level C libraries that also should-but-don't take a const-correct pointer.  So then the C++ code either has to const_cast it away, or we have to similarly modify the C library accordingly.  It's a difficult mess to untangle.

**Comment by zack-vii** [comment]
started to add const where applicable in mdsshr.

const type value; // const value
const type *ptr; // pointer on const value
type *const ptr; // const pointer on value
