### ISSUE TITLE
jScope interprets Uint16 as Int16 before rendering

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#908]
Dear All,

data samples from 16-bit ADC stored as Uint16 appears like this

![image](https://cloud.githubusercontent.com/assets/5898559/25534597/89b8095c-2c34-11e7-81e5-98f7787903d5.png)

if downloaded and plotted with python (Uint16 type preserved, values are betwen 0 ad 65535)
and like this

![image](https://cloud.githubusercontent.com/assets/5898559/25534187/509b666a-2c33-11e7-8f50-e5d03811f9f5.png)

on the jScope (Unit16 data cast to Int16 type, some values are negative)

Not really a problem for me at the moment (I do not intend to plot raw data), but probably it was not the intended behaviour.

Sincerely,

**Comment by alkhwarizmi** [comment]
Hi all, I have updates about this problem.

It seems that data is stored correctly in the database. When I change the jScope data provider from MdsDataProvider to LocalDataProvider values are plotted correctly.

However, MdsDataProvider is the right data provider for me.

Sincerely,

**Comment by tfredian** [comment]
Hi, I am hoping that Gabriele, one of the authors of jScope, will be able to check on this at some point. I suspect the problem is how tdi handles subscripting of 2-D arrays. If you look at the following results in tditest you will see that in one case the subscripting result is a 2-D array:

_z=[[1,2],[3,4],[5,6],[7,8]]
shape(_z[\*,0])
[2]
shape(_z[0,\*])
[1,4]

This behavior of tdi has been there for decades and unfortunately there are probably expressions stored in data files that may depend on this behavior so we cannot change tdi. However, applications such as jScope should detect 2-D arrays with 1 row or column and treat them as a vector. An ugly but easy
workaround is to use something like the following in you scope panel until the code in jScope is updated:

  _ans=_z[0,*],set_range(size(_ans),_ans)
  [1,3,5,7]

This will flatten the result of the subscripting and hopefully correct the result in jScope.

**Comment by alkhwarizmi** [comment]
Thank you Tom,

you are always quick and effective in the replies.  I think you spotted the source of the asymmetric behavior. I am just wondering if this is the answer to issue #907, or in your opinion the #907 and this issue are related?

Sincerely,

**Comment by alkhwarizmi** [comment]
I have spotted another strange difference between LocalDataProvider and MdsDataProvider in the jScope.

The bottom axis of the following pictures is configured as follows:

![image](https://cloud.githubusercontent.com/assets/5898559/25618990/713f5598-2f49-11e7-93b0-124bd280e4c0.png)

"exchangetest" is my remote test MDSplus server.

If I "render" the scope with the LocalDataProvider, is becomes (slowly) like

![image](https://cloud.githubusercontent.com/assets/5898559/25619070/cfb3cc62-2f49-11e7-85ac-3e6cff5ff721.png)

If I "render" it with the MdsDataProvider, the third line is not rendered at all.

![image](https://cloud.githubusercontent.com/assets/5898559/25619128/09a2a86c-2f4a-11e7-94c5-0cc5b765e711.png)

This doesn't seem a problem of TDI per sè, but something done (or not done) on the expressions by the DataProviders.

I know that Gabriele is looking into that, I keep posting here because I think it is good to store the comments in the GitHub platform.

Sincerely,

**Comment by GabrieleManduchi** [comment]
a bit late.....but now it is fixed,
