### ISSUE TITLE
Mismatching versions of MDSObjects for Python and Python MDSObjects installation

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#962]
Dear all,

trying to solve an annoying problem with MDSplus devices and python3.4 (from Anaconda distribution) I noticed that the Python software package at the site https://pypkg.com/pypi/mdsplus/ (an on my installation MDSplus alpha 7.8.0) is different from the current alpha version of it (I have pulled the the last alpha branch).

In the former case, MDSplusExceptions is a python submodule (a directory where the exceptions seems to have been organized in different files for clarity, with their own `__init__.py` defining the MDSplusException). In the latter case, MDSplusExceptions.py is a single file.

Can somebody clarify what is the first website and from where did they pick the code? How many ways there are to install the python bindings of mdsobjects? What is the right way to install it (usually installing MDSplus leaves the python mdsobjects in a not working state and I have to run manually 

`python setup.py install` 

from the installation directory)? I think I have some doubt on this matter and I would like to avoid pointing colleague of mine in the wrong direction.

Sincerely,

**Comment by tfredian** [comment]
We definitely need to do a better job with this. I am inclined to discontinue providing an MDSplus package on pypi since the python code needs to match the rest of the MDSplus software package. We did find a problem with the python installer kit for Windows which prevented it from installing MDSplus in the default python on the system when installing MDSplus and this should be fixed now. Users can use pip to install the module from the /usr/local/mdsplus/mdsobjects/python directory as a user package if they don't have root/administrator privileges.

 pip install --user [--upgrade] /usr/local/mdsplus/mdsobjects/python

We will discuss this and perhaps discontinue the pypi distribution of MDSplus since it seems to just cause trouble.

**Comment by alkhwarizmi** [comment]
I confirm that MDSplus Alpha 7.15.5 installs the mdsobjects Python bindings correctly with Anaconda3 and Python 3.6 on Windows 10.

Not so the current MDSplus Stable 7.7.5 version.

Thank you Tom!
